version: '3.8'
services:

# force db migration if needed via docker exec -it odoo sh
# odoo --init base --database odoo --stop-after-init --db_host=db --db_user odoo --db_password odoo
  app:
    image: fbieringer/odoo:16-arm64
    container_name: odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ..:/mnt/extra-addons/apprise
    network_mode: service:db
  db:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5432:5432
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo

volumes:
  pg-data:
  odoo-data:
